###Product Index
GET http://localhost:3000/products.json

###Product Show
GET http://localhost:3000/products/2.json

###Product Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Torch",
  "price": 13,
  "image_url": "frankestiens_monsters_fears.jpeg",
  "description": "Something frankenstien's monster is very afraid of"
}

###Product Update
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Banana_and_cross_section.jpg/1024px-Banana_and_cross_section.jpg"
}

###Product Destroy
DELETE http://localhost:3000/products/8.json

