@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNjE0MTR9.xuoZI00jMMGEMQgGGtoMZAjFdKnGPVg6LO1ldh_4Xh4

###Product Index
GET http://localhost:3000/products.json

###Product Show
GET http://localhost:3000/products/2.json

###Product Create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Razer",
  "price": 10000,
  "image_url": "frankestiens_monsters_fears.jpeg",
  "description": "phone of old",
  "supplier_id": 3
}

###Product Update
PATCH http://localhost:3000/products/18.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "price": 11000
}

###Product Destroy
DELETE http://localhost:3000/products/12.json

