@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNjE0MTR9.xuoZI00jMMGEMQgGGtoMZAjFdKnGPVg6LO1ldh_4Xh4

###Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

###Orders Show
GET http://localhost:3000/orders/7.json
Authorization: Bearer {{jwt}}


###Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}