@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1NzIwMzJ9.l5gqF-SFZuQYxmwkg0eTTv22tyMoSULIUAEbHIqKmkA

###Orders Index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

###Orders Show
GET http://localhost:3000/orders/7.json
Authorization: Bearer {{jwt}}


###Orders Create
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}