### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "2Test name",
  "email": "2test@test.com",
  "password": "2password",
  "password_confirmation": "2password"
}