### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name2",
  "email": "test2@test.com",
  "password": "password2",
  "password_confirmation": "password2"
}