@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDg1ODc3Mzh9.WPmt4ryOEYoAV5QHljGst8xVAhuxEaYDpxTBltBmenE

###Index Current User Cart
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}


###Create Cart
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 2
}

###Orders Delete
DELETE http://localhost:3000/carted_products/29.json
Authorization: Bearer {{jwt}}